### ISSUE TITLE
Error on running CANTM : Run CANTM: bash runCANTM_covid.sh

### ISSUE THREAD

**Issue by SangRyul** [GateNLP/CANTM#2]
Hello I have a problem with
```sh
Run CANTM: bash runCANTM_covid.sh
Run BERT: bash runBert_covid.sh
Run NVDM: runNVDM_covid.sh
Run NVDM_bert: runNVDM_bert_covid.sh
Run LDA: runLDA_covid.sh
```
when I run `bash runCANTM_covid.sh`, then i got this error message

```sh
Traceback (most recent call last):
  File "evaluation.py", line 69, in <module>
    evaluaton.cross_fold_evaluation()
  File "/home/super/sr_work/paper_review/CANTM/GateMIcateLib/EvaluationManager.py", line 295, in cross_fold_evaluation
    self.train(cache_path=fold_cache_path)
  File "/home/super/sr_work/paper_review/CANTM/GateMIcateLib/EvaluationManager.py", line 258, in train
    self.mUlti.train(trainBatchIter, cache_path=cache_path, num_epohs=self.num_epoches, valBatchIter=valBatchIter, patience=self.patient, earlyStopping=self.earlyStopping)
  File "/home/super/sr_work/paper_review/CANTM/GateMIcateLib/modelUlti.py", line 30, in train
    for current_prediction in trainIter:
  File "/home/super/sr_work/paper_review/CANTM/GateMIcateLib/modelUlti.py", line 96, in pred
    for x, y in batchGen:
  File "/home/super/sr_work/paper_review/CANTM/GateMIcateLib/BatchIter.py", line 28, in __next__
    current_batch_x, current_batch_y = self._readNextBatch()
  File "/home/super/sr_work/paper_review/CANTM/GateMIcateLib/BatchIter.py", line 47, in _readNextBatch
    x, y = next(self.dataIter)
  File "/home/super/sr_work/paper_review/CANTM/GateMIcateLib/readers/ReaderBase.py", line 31, in __next__
    current_sample = self._readNextSample()
  File "/home/super/sr_work/paper_review/CANTM/GateMIcateLib/readers/ReaderBase.py", line 46, in _readNextSample
    current_sample = self.postProcessor.postProcess(current_sample)
  File "/home/super/sr_work/paper_review/CANTM/GateMIcateLib/ScholarPostProcessor.py", line 153, in postProcess
    current_rawx = self._get_sample(sample, x_field)
  File "/home/super/sr_work/paper_review/CANTM/GateMIcateLib/PostprocessorBase.py", line 99, in _get_sample
    current_rawx = sample[sample_field]
KeyError: 'Claim'
```
my environment is : ubuntu18.04 with 8 RTX 2080TI GPUS, and my python version is 3.8.3

How do I have to do to solve this problem?

Thanks a lot.

**Comment by deansong** [comment]
From the error message, it seems the data is not corrected downloaded. Do you have any error message from 
"getCovidData.sh"

**Comment by SangRyul** [comment]
actually we have to download 1293 crawling datas with firefox engine. It took a long time to download, even there is a error message;Timeout of selenium. 
```sh
1289 1293
Traceback (most recent call last):
  File "downloadIFCNSource.py", line 43, in <module>
    claim,explain,country,date,factcheck_Org = download_source(each_data['Link'])
  File "downloadIFCNSource.py", line 12, in download_source
    driver.get(url)
  File "/home/super/anaconda3/envs/wvmisinfoGPU/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/super/anaconda3/envs/wvmisinfoGPU/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in exec
    self.error_handler.check_response(response)
  File "/home/super/anaconda3/envs/wvmisinfoGPU/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in csponse
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

So I didn't downloaded the full data. So I reduce the number, and then I could get the merged_clean_ml.json(with reduced numer of data). after that I run the CANTM_covid.sh.

So Can you share the data before I run the CANTM_covid.sh? or do I have to change the code of crawling data?

And I wonder the error message : KeyError : 'Claim', I checked in the json file, there is a key "Claim"

Thanks a lot.

**Comment by deansong** [comment]
I send you the data via email, let me know if you still get the error.

**Comment by rexysihombing** [comment]
Halo @SangRyul 

Do you have a Demo of this project?
So, I can follow to running it on my machine (Windows 10)
Thank you.

**Comment by deansong** [comment]
Hi @rexysihombing 

We have a web demo running here https://cloud.gate.ac.uk/shopfront/displayItem/covid19-misinfo
There is a REST API for this project as well "https://cloud-api.gate.ac.uk/process/covid19-misinfo" you can run it with any system. Here is the guide of our API:https://cloud.gate.ac.uk/info/help/online-api.html
